name: Unit Tests and coverage report

on:
  workflow_dispatch:
  push:
    branches:
        - main
    paths:
        - "ReviewParser.js"
        - "TaskObject.js"
        - "test/**"
        - "WATCHER-test-files/**"
  pull_request:
    branches:
        - main
    paths:
        - "ReviewParser.js"
        - "TaskObject.js"
        - "test/**"
        - "WATCHER-test-files/**"

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install app dependencies
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Upload coverage to github
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: coverage
        path: coverage
  
